- hosts: Docker
  tasks:
    - name: Copy docker-database from ansibleHost to dockerHost
      copy:
        src: /home/Chakhree/docker/docker-database/
        dest: /home/Chakhree/docker/docker-database/
    - name: Remove Ansiblefie in dockerHost
      ansible.builtin.shell: |
        sudo rm -rf /home/Chakhree/docker/docker-database/Ansiblefile.yaml
      ignore_errors: true
    - name: Stop and remove containers
      ansible.builtin.shell: |
        docker stop mongo-container 
        docker rm mongo-container
        docker stop mysql-container 
        docker rm mysql-container
        docker stop postgres-container 
        docker rm postgres-container
      ignore_errors: true
