- hosts: Docker
  tasks:
    - name: Copy docker-database from ansibleHost to dockerHost
      copy:
        src: /home/Chakhree/docker/docker-database/
        dest: /home/Chakhree/docker/docker-database/
    - name: Stop and remove nestjs-pnpm-container
      ansible.builtin.shell: |
        sudo rm -rf /home/Chakhree/docker/docker-database/Ansiblefile.yaml
      ignore_errors: true
