version: "3"

services:
  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_backup:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "docker"
      MYSQL_USER: "ec2_mysql"
      MYSQL_PASSWORD: "p7yFwLE9rS5Q4UHC27czraTJ"
      MYSQL_ROOT_PASSWORD: "root"
# # ---------- optional ----------

# phpmyadmin:
#   image: phpmyadmin
#   container_name: phpmyadmin-container
#   restart: always
#   ports:
#     - 8080:80
#   environment:
#     PMA_HOST: mysql
#     PMA_PORT: 3306

