version: "3.9"
services:
  cassandra:
    image: cassandra
    container_name: cassandra-container
    restart: always
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_USER: "ec2-user@cassandra"
      CASSANDRA_PASSWORD: "zJqImQR4kyJsveGZ"
    volumes:
      - ./cassandra_backup:/var/lib/cassandra
