version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: "ec2-user@postgres"
      POSTGRES_PASSWORD: "eLuIEr)Vvkuyg3++"
      POSTGRES_DB: "docker"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_backup:/var/lib/postgresql/data
volumes:
  db-data:
