version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: "ec2_postgres"
      POSTGRES_PASSWORD: "RDUQvgEYYU5ZWHjqzVTSn2Ix"
      POSTGRES_DB: "docker"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_backup:/var/lib/postgresql/data
volumes:
  db-data:
