version: "3.7"
services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "ec2-user@mongo"
      MONGO_INITDB_ROOT_PASSWORD: "f2tTNQHxVmZZ3Ew+"
      MONGO_INITDB_DATABASE: "docker"
    volumes:
      # - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo_backup:/data/db
